version: '3'

services:
    webserver:
        build: .
        command: python3 manage.py runserver 0.0.0.0:7000
        volumes:
            - .:/app
        ports:
            - 7000:7000
        env_file:
            - .env
        depends_on:
            - db

    db:
        # 公式からイメージをpull
        image: postgres:12.0-alpine
        # データベースの永続化
        # ホストのディレクトリにマウントしない様、先頭に`./`をつけない
        volumes:
            - postgres_data:/var/lib/postgresql/data

# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data: