version: '3'

services:
    db:
        image: postgres

    webserver:
        build: .
        command: python3 manage.py runserver 0.0.0.0:7000
        volumes:
            - .:/app
        ports:
            - 7000:7000
        depends_on:
            - db